# Dockerfile
FROM python:3.12-slim

# Установка зависимостей ОС
RUN apt-get update && apt-get install -y \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# Рабочая директория
WORKDIR /app

# Копируем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем проект
COPY . .

# Собираем статику (на случай, если нужно)
RUN python manage.py collectstatic --noinput

# Порт
EXPOSE 8000

# Запуск
CMD ["gunicorn", "OpenWorld.wsgi:application", "--bind", "0.0.0.0:8000"]