# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: openworld_db
      POSTGRES_USER: openworld_user
      POSTGRES_PASSWORD: openworld_pass
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    # Для продакшена замени на: gunicorn OpenWorld.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-g3^jiaf!9gj@p+*buq+*91)80#xjzsemiau**4lgowpohq@l@y
      - DB_NAME=openworld_db
      - DB_USER=openworld_user
      - DB_PASSWORD=openworld_pass
      - DB_HOST=db
      - DB_PORT=5432
      - ALLOWED_HOSTS=*
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
  static_volume: