# Generated by Django 5.2.6 on 2025-09-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='id')),
                ('image_url', models.URLField(verbose_name='Адрес картинки')),
                ('title', models.CharField(verbose_name='Название')),
                ('category', models.CharField(verbose_name='Категория')),
                ('tags', models.CharField(verbose_name='Теги')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
        ),
    ]
